### ISSUE TITLE
Eventually delete this repository

### ISSUE THREAD

**Issue by werebus** [umts/umasstransit.st.rodeo#1]
Just wanted to document that I think (open to discussion) that we probably shouldn't have two slightly different roadeo applications with mostly the same codebases. Thoughts?

**Comment by dfaulken** [comment]
Right, I think the intention is that for next year, since we'll have more lead time, we can work on making the original codebase more adaptable to both bus and paratransit.

**Comment by Anbranin** [comment]
Exactly. This could provide an excellent exercise for new programmers.

**Comment by werebus** [comment]
Welp, looks like we're pushing this to 2019.

**Comment by werebus** [comment]
It was bugging me that the two trees were unrelated histories, so I reconstructed them as if we had forked instead of an FS copy.

**Comment by werebus** [comment]
https://github.com/umts/umasstransit.rodeo/tree/st
